api:
  key: ${env.API_KEY}
  url: ${env.API_URL}
elasticsearch:
  host: ${env.ELASTICSEARCH_HOST}
  port: ${env.ELASTICSEARCH_PORT}
spring:
  batch:
    initialize-schema: always
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: ${env.DATABASE_PLATFORM}
    url: ${env.DATABASE_URL}
    username: ${env.DATABASE_USERNAME}
    password: ${env.DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
